#!/usr/bin/env php

<?php

class Appmanager{

    private string $app_json;
    private string $app_log;
    private string $path;

    public function __construct()
    {

        $this->path = getenv("HOME");
        $this->app_json = $this->path . "/appmanager/app_command.json";
        $this->app_log = $this->path . "/appmanager/log";
        
    }

    public function run(string $command, string $app_text) : void{

        //============================================
        // Creating folder and json file
        //============================================

        if(!is_dir($this->path . "/appmanager")) mkdir($this->path . "/appmanager", 0755, true);

        if(!is_dir($this->app_log)) mkdir($this->app_log, 0755, true);

        if(!file_exists($this->app_json)) file_put_contents($this->app_json, "[]", LOCK_EX);

        match($command){

            "home" => $this->Home_command(),

            "add" => $this->Add_command(),

            "reset" => $this->Reset_command(),

            "delete" => $this->Delete_command(),

            "list" => $this->List_command(),

            "run" => $this->Run_command($app_text),

            "log" => $this->Clear_logs($app_text),

            default => (function(){

                echo "\n";
                echo "Command not found\n";
                echo "Use : appmanager or php appmanager\n";
                echo "Use : appmanager list or php appmanager list\n";
                echo "Use : appmanager add or php appmanager add\n";
                echo "Use : appmanager delete or php appmanager delete\n";
                echo "Use : appmanager reset or php appmanager reset\n";
                echo "Use : appmanager run [id] or php appmanager run [id]\n";
                echo "Use : appmanager log clear or php appmanager log clear\n";

            })()

        };

    }

    private function Home_command(): void{

        echo "App:\n\n";

        //===================================
        // All app list
        //===================================

        $app_list = json_decode(file_get_contents($this->app_json), true) ?? []; 

        if(empty($app_list)){

            $this->save_log("INFO", "No Apps Found");

            echo "[INFO] No Apps Found.\n\n";

            echo "> First add an app:\n";
            echo "   appmanager add or php appmanager add\n\n";

            echo "> Available commands:\n";
            echo "   appmanager list or php appmanager list\n";
            echo "   appmanager add or php appmanager add\n";
            echo "   appmanager delete or php appmanager delete\n";
            echo "   appmanager reset or php appmanager reset\n";
            echo "   appmanager run [id] or php appmanager run [id]\n";
            echo "   appmanager log clear or php appmanager log clear\n";

            exit;

        }

        foreach ($app_list as $app){

            $this->output($app["app_id"], $app["app_title"]);

        }

        echo "\n";
        echo "App id:\n";

        $user_app_id = readline("=>");      // user input

        $s_user_app_id = trim(preg_replace("/[^\p{N}]/", "", $user_app_id ?? ""));    //sanitize user input

        if(empty($s_user_app_id)){

            $this->save_log("ERROR", "Invalid id");

            echo "[ERROR] Invalid id\n";
            exit;

        }

        //search number
        $isFound = false;
        $app_title = "";
        $app_command = [];

        foreach ($app_list as $list){

            if(($list["app_id"] ?? null) == $s_user_app_id){

                $isFound = true;
                $app_title = $list["app_title"];
                $app_command = $list["app_command"];
                break;

            }

        }

        if(!$isFound){

            $this->save_log("ERROR", "Not found");

            $this->app_print("[ERROR] Not found");

        }

        echo "\033[H\033[J";

        echo "================================================\n";
        echo"$app_title\n";
        echo "================================================\n";
        
        foreach ($app_command as $command){

            if(!empty($command)){

                $this->save_log("COMMAND", "[$command] is executed");

                passthru(escapeshellcmd($command) . " 2>&1");

            }

        }

    }//fun end

    private function Add_command(): void{

        //initil items
        $id = "";
        $title = "";
        $first_command = "";
        $second_command = "";
        $third_command = "";
        $fourth_command = "";
        $fifth_command = "";

        $is_single_command = false;
        $is_multiple_command = false;

        echo "Select Command:\n";
        $this->output("1", "Single command");
        $this->output("2", "Multiple command");

        //========================
        //User input
        //========================

        echo "\n";
        $selected_id = readline("=>");
        echo "\n";

        if($selected_id === "1"){

            $is_single_command = true;

            echo "App id :\n";
            $id = readline("=>");
            echo "\n";

            echo "App title :\n";
            $title = readline("=>");
            echo "\n";

            echo "App command :\n";
            $first_command = readline("=>");


        }elseif($selected_id === "2"){

            $is_multiple_command = true;

            echo "App id :\n";
            $id = readline("=>");
            echo "\n";

            echo "App title :\n";
            $title = readline("=>");
            echo "\n";

            echo "1st command :\n";
            $first_command = readline("=>");
            echo "\n";

            echo "2nd command :\n";
            $second_command = readline("=>");
            echo "\n";

            echo "3rd command :\n";
            $third_command = readline("=>");
            echo "\n";

            echo "4th command :\n";
            $fourth_command = readline("=>");
            echo "\n";

            echo "5th command :\n";
            $fifth_command = readline("=>");

        }else{

            $this->save_log("ERROR", "Invalid id");
            $this->app_print("[ERROR] Invalid id");

        }

        //=============================
        //Sanitizing data
        //=============================

        $s_id = trim(preg_replace("/[^\p{N}]/", "", $id ?? ""));
        $s_title = trim($title);
        $s1st_command = trim($first_command);
        $s2nd_command = trim($second_command);
        $s3th_command = trim($third_command);
        $s4th_command = trim($fourth_command);
        $s5th_command = trim($fifth_command);

        //===========================
        //Empty data checks
        //===========================

        if($is_single_command){

            if(empty($s_id) || empty($s_title) || empty($s1st_command)){

                $this->save_log("ERROR", "[$id] [$title] [$first_command] Invalid id / text / command");

                $this->app_print("[ERROR] Invalid id / text / command");

            }

        }else{

            if((empty($s_id) || empty($s_title)) || (empty($s1st_command) && 
            empty($s2nd_command) && empty($s3th_command) && empty($s4th_command) && empty($s5th_command))){

                $this->save_log("ERROR", "[$id] [$title] [$first_command] [$second_command] [$third_command] [$fourth_command] [$fifth_command] Invalid id / text / command");

                $this->app_print("[ERROR] Invalid id / text / command");

            }

        }

        //================================
        //Check app in list
        //================================

        $app_list = json_decode(file_get_contents($this->app_json), true) ?? [];

        if(!empty($app_list)){

            foreach ($app_list as $app){

                if(($app["app_id"] ?? null) == $s_id){

                    $this->save_log("ERROR", "[$s_id] Duplicate app found");

                    $this->app_print("[ERROR] Duplicate app found");

                }

            }

        }

        //===============================
        //Insert user app in list
        //===============================

        if($is_single_command){

            $data = [

                "app_id" => $s_id,
                "app_title" => $s_title,
                "app_command" => [ $s1st_command ]

            ];

        }else{

            $data = [

                "app_id" => $s_id,
                "app_title" => $s_title,
                "app_command" => [ 

                    $s1st_command ?? "",
                    $s2nd_command ?? "",
                    $s3th_command ?? "",
                    $s4th_command ?? "",
                    $s5th_command ?? ""

                 ]

            ];

        }

        $app_list[] = $data;

        $insert = file_put_contents($this->app_json, json_encode($app_list, JSON_PRETTY_PRINT | 
        JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE), LOCK_EX);

        chmod($this->app_json, 0600);
            
        if(!$insert){

            $this->save_log("ERROR", "App not saved");

            $this->app_print("[ERROR] App not saved");

        }

        $this->save_log("OK", "[$title] App saved successful");

        $this->app_print("[OK] App saved successful");
            
    }//fun end

    private function Delete_command(): void{

        echo "App id:\n";

        $id = readline("=>"); //user input

        $s_id = trim(preg_replace("/[^\p{N}]/", "", $id ?? ""));  //sanitize id

        if(empty($s_id)){

            $this->save_log("ERROR", "[$id] Invalid id");

            $this->app_print("[ERROR] Invalid id");

        }

        //================================
        //Check app in list
        //================================

        $app_list = json_decode(file_get_contents($this->app_json), true) ?? [];
        $isDeleted = false;

        if(!empty($app_list)){

            foreach ($app_list as $index => $app){

                if(($app["id"] ?? null) == $s_id){

                    unset($app_list[$index]);
                    $isDeleted = true;
                    break;

                }

            }

        }

        if($isDeleted){

            $app_list = array_values($app_list);

            file_put_contents($this->app_json, json_encode($app_list, JSON_PRETTY_PRINT | 
                JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE), LOCK_EX);

            $this->save_log("OK", "Delete successful");

            $this->app_print("[OK] Delete successful");

        }

        $this->save_log("ERROR", "Delete failed");

        $this->app_print("[ERROR] Delete failed");
        
    }//fun end

    private function Reset_command(): void{

        $isUserConfirmed = false;

        $app_list = json_decode(file_get_contents($this->app_json), true) ?? [];

        if(empty($app_list)){

            $this->save_log("INFO", "Empty app list");

            echo "[INFO] Empty app list\n\n";

            echo "> Add your first app:\n";
            echo "   appmanager or php appmanager add\n\n";
            exit;

        }

        echo "Are you sure you want reset all [Y/n]:\n";

        $input = readline("=>");    //user input

        $s_input = trim(preg_replace("/[^a-zA-Z]/", "", $input ?? ""));     //sanitize user input

        if(empty($s_input)){

            $this->save_log("ERROR", "[$input] Invalid text");

            $this->app_print("[ERROR] Invalid text");

        }

        if(strtolower($s_input) === "y"){

            $isUserConfirmed = true;

        }else{

            $isUserConfirmed = false;

        }

        if($isUserConfirmed){

            file_put_contents($this->app_json, "[]", LOCK_EX);

            $this->save_log("OK", "Reset successful");

            $this->app_print("[OK] Reset successful");

        }

        $this->save_log("ERROR", "Reset failed");
        $this->app_print("[ERROR] Reset failed");
            
    }//fun end

    private function List_command(): void{

        $green_color = "\033[32m";
        $bold_text = "\e[1m";
        $reset = "\e[0m";

        //===============================
        // App list
        //===============================
            
        $app_list = json_decode(file_get_contents($this->app_json), true) ?? [];

        if(!empty($app_list)){

            echo " No  >> Name    >> Command\n\n";

            //==============================
            // Get all app list
            //==============================

            foreach ($app_list as $app_data){

                $id = $app_data["app_id"];
                $title = $app_data["app_title"];
                $command = $app_data["app_command"];

                $command = "[ " . implode(" ], [ ", $command) . " ]";

                printf(" %-3s >> %-15s >> %-70s \n", $id, $bold_text . $title . $reset, $green_color . $bold_text . $command . $reset);

            }


        }else{

            $this->save_log("INFO", "Empty app list");

            echo "[INFO] Empty app list\n\n";

            echo "> Add your first app:\n";
            echo "   appmanager add or php appmanager add\n\n";

        }

    }//fun end

    private function Run_command(string $app_id) : void{

        //=================================
        // Sanitizing the id
        //=================================
        $s_app_id = preg_replace("/[^\p{N}]/", "", $app_id);

        $app_list = json_decode(file_get_contents($this->app_json), true) ?? [];

        if(empty($s_app_id)){

            $this->app_print("[ERROR] Invalid id");
            $this->save_log("ERROR", "[$app_id] Invalid id");

        }

        if(!empty($app_list)){

            $isFound = false;
            $app_id = "";
            $app_command = [];

            //==============================
            // Search app id in list
            //==============================

            foreach ($app_list as $list){

                if(($list["app_id"] ?? null) == $s_app_id){

                    $isFound = true;
                    $app_id = $list["app_id"];
                    $app_command = $list["app_command"];
                    break;

                }

            }

            if(!$isFound){

                $this->app_print("[ERROR] App not found");
                $this->save_log("ERROR", "[$s_app_id] Not found in list");

            }

            foreach ($app_command as $command){

                $this->save_log("COMMAND", "[$command] is executed");

                passthru(escapeshellcmd($command) . " 2>&1");

            }


        }else{

            $this->app_print("[ERROR] Not found");
            $this->save_log("ERROR", "App list not found");

        }

    }//fun end

    private function Clear_logs(string $text) : void{

        if($text !== "clear"){

            $this->save_log("INFO", "Use : app log clear or php app log clear");
            $this->app_print("[INFO] Use : app log clear or php app log clear");

        }

        echo "Are you sure? [Y/n]:\n";
        $user_confirmation = readline("=>");

        if(strtolower($user_confirmation) === "y"){

            $files = glob($this->app_log . "/*.txt");

            foreach ($files as $file){

                unlink($file);

            }

            $this->save_log("OK", "Logs deleted successfully");
            $this->app_print("[OK] Logs deleted successfully");

        }else{

            $this->save_log("ERROR", "Logs delete failed");
            $this->app_print("[ERROR] Logs delete failed");

        }


    }//fun end

    private function output(string $number, string $text) : void{

        $green_color = "\033[32m";
        $bold_text = "\e[1m";
        $reset = "\e[0m";

        echo "[" . $green_color . $bold_text . $number . $reset . "]" . " " . $green_color . $bold_text . $text . $reset . "\n";

    }//fun end

    private function app_print(string $text) : void{

        echo "\n";
        echo "$text\n";
        exit;

    }//fun end

    private function save_log(string $type, string $message){

        date_default_timezone_set("UTC");

        $date = date("Y-m-d h:i:s A");

        //=============================
        // Monthly log file
        //=============================

        $month = date("Y-m");

        $log = "[$date] >> [$type] >> $message";

        file_put_contents($this->app_log . "/{$month}_log.txt", $log . PHP_EOL, FILE_APPEND);

    }//fun end


}//class

$command = $argv[1] ?? "home";
$app_text = $argv[2] ?? "";
$appmanager = new Appmanager();
$appmanager->run($command, $app_text);

